apiVersion: v1
kind: Service
metadata:
  labels:
    app: insure_tech_service
  name: insure-tech-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
      app: insure-tech-01
